# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('narrative', models.TextField(blank=True)),
                ('kpi_claims', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('extracted_kpis', models.JSONField(blank=True, default=list)),
                ('extraction_demo', models.BooleanField(default=False)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_report', to='pilots.pilot')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_final_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveIntegerField()),
                ('narrative', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('kpi_claims', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted on time'), ('LATE', 'Late'), ('VERIFIED', 'Verified'), ('NEEDS_CLARIFICATION', 'Needs clarification'), ('REJECTED', 'Rejected')], default='PENDING', max_length=32)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('delay_reason', models.TextField(blank=True)),
                ('delay_review', models.CharField(blank=True, max_length=32)),
                ('delay_review_note', models.TextField(blank=True)),
                ('verification_status', models.CharField(blank=True, max_length=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('ai_progress', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='pilots.pilot')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_weekly_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['week'],
                'unique_together': {('pilot', 'week')},
            },
        ),
        migrations.CreateModel(
            name='FieldVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('VERIFIED', 'Verified'), ('NEEDS_CLARIFICATION', 'Needs clarification'), ('NOT_VERIFIED', 'Not verified')], max_length=32)),
                ('observations', models.TextField(blank=True)),
                ('activity_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_verifications', to='pilots.pilot')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_verifications', to=settings.AUTH_USER_MODEL)),
                ('final_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='reports.finalreport')),
                ('weekly_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='reports.weeklyreport')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyKPIResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('evidence_ref', models.CharField(blank=True, max_length=240)),
                ('note', models.CharField(blank=True, max_length=400)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_results', to='pilots.kpi')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reports.weeklyreport')),
            ],
            options={
                'unique_together': {('report', 'kpi')},
            },
        ),
    ]
