from django.contrib import admin
from django.urls import path

from common import endpoints as core
from common import endpoints_workflow as flow

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/health/", core.health),
    path("api/meta/", core.meta),
    path("api/demo-accounts/", core.demo_accounts),
    path("api/auth/login/", core.login),
    path("api/auth/logout/", core.logout),
    path("api/auth/register/", core.register),
    path("api/auth/me/", core.me),
    path("api/employees/", core.employees),
    path("api/problem-statements/", core.problem_list),
    path("api/problem-statements/<int:pk>/", core.problem_detail),
    path("api/problem-statements/<int:pk>/assign/", core.problem_assign),
    path("api/match/problem-statements/", core.startup_matches),
    path("api/startups/", core.startup_list),
    path("api/startups/<int:pk>/", core.startup_detail),
    path("api/applications/", flow.application_list),
    path("api/applications/<int:pk>/", flow.application_detail),
    path("api/applications/<int:pk>/eligibility/", flow.application_eligibility),
    path("api/applications/<int:pk>/clarification-response/", flow.clarification_response),
    path("api/documents/", flow.document_list),
    path("api/documents/expiry-scan/", flow.expiry_scan),
    path("api/documents/<int:pk>/", flow.document_detail),
    path("api/documents/<int:pk>/download/", flow.document_download),
    path("api/documents/<int:pk>/verify/", flow.document_verify),
    path("api/documents/<int:pk>/expiry/", flow.document_expiry),
    path("api/evaluations/", flow.evaluation_list),
    path("api/evaluations/<int:pk>/", flow.evaluation_detail),
    path("api/pilots/", flow.pilot_list),
    path("api/pilots/<int:pk>/", flow.pilot_detail),
    path("api/pilots/<int:pk>/kpis/", flow.pilot_kpis),
    path("api/pilots/<int:pk>/lock-kpis/", flow.lock_kpis),
    path("api/pilots/<int:pk>/send-contract/", flow.send_contract),
    path("api/pilots/<int:pk>/contract-file/", flow.contract_file),
    path("api/pilots/<int:pk>/sign/", flow.sign_contract),
    path("api/pilots/<int:pk>/confirm-extracted-kpis/", flow.confirm_extracted),
    path("api/pilots/<int:pk>/assign-field/", flow.assign_field),
    path("api/pilots/<int:pk>/cancel/", flow.cancel_pilot),
    path("api/pilots/<int:pk>/reports/", flow.submit_report),
    path("api/pilots/<int:pk>/delay-excuse/", flow.delay_excuse),
    path("api/pilots/<int:pk>/delay-review/", flow.review_delay),
    path("api/pilots/<int:pk>/verify-report/", flow.verify_report),
    path("api/pilots/<int:pk>/final-report/", flow.final_report),
    path("api/pilots/<int:pk>/verify-result/", flow.verify_result),
    path("api/pilots/<int:pk>/score/", flow.pilot_score),
    path("api/pilots/<int:pk>/recommendation/", flow.recommendation_detail),
    path("api/complaints/", flow.complaint_list),
    path("api/complaints/<int:pk>/respond/", flow.complaint_respond),
    path("api/alerts/", flow.alerts),
    path("api/notifications/", flow.notifications),
    path("api/notifications/<int:pk>/read/", flow.notification_read),
    path("api/leaderboard/", flow.leaderboard),
    path("api/recommendations/", flow.recommendation_list),
    path("api/recommendations/<int:pk>/", flow.recommendation_detail),
    path("api/dashboard/", flow.dashboard),
    path("api/audit-logs/", flow.audit_logs),
    path("api/ai/analyze-proposal/", flow.ai_analyze_proposal),
    path("api/ai/extract-contract-kpis/", flow.ai_extract_contract),
    path("api/ai/extract-weekly-kpis/", flow.ai_extract_weekly),
    path("api/ai/analyze-progress/", flow.ai_progress),
    path("api/ai/analyze-final-performance/", flow.ai_final),
    path("api/ai/generate-scaleup-recommendation/", flow.ai_scaleup),
    path("api/ai/generate-report/", flow.ai_report),
    path("api/ai/summarize/", flow.ai_summarize),
]
