# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=160)),
                ('technologies', models.CharField(max_length=400)),
                ('dpiit_number', models.CharField(blank=True, max_length=64)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=80)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('team_size', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('capabilities', models.TextField(blank=True)),
                ('relevant_experience', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
    ]
