# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESPONSE_REQUESTED', 'Startup response requested'), ('RESPONDED', 'Startup responded'), ('ACCEPTED', 'Explanation accepted'), ('ESCALATED', 'Escalated'), ('CLOSED', 'Closed')], default='OPEN', max_length=32)),
                ('startup_response', models.TextField(blank=True)),
                ('officer_action', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='pilots.pilot')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_raised', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
