# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=160)),
                ('technology_domain', models.CharField(max_length=160)),
                ('expected_outcome', models.TextField()),
                ('technical_requirements', models.JSONField(default=list)),
                ('eligibility_criteria', models.JSONField(default=list)),
                ('required_documents', models.JSONField(default=list)),
                ('application_deadline', models.DateField()),
                ('pilot_joining_deadline', models.DateField()),
                ('pilot_location', models.CharField(max_length=240)),
                ('pilot_duration_weeks', models.PositiveIntegerField(default=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PILOT_ACTIVE', 'Pilot active'), ('PILOT_COMPLETED', 'Pilot completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_problems', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='problem_statements', to='accounts.department')),
                ('procurement_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procuring_problems', to=settings.AUTH_USER_MODEL)),
                ('technical_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluating_problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
