# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pilots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, choices=[('CONSIDER_PROCUREMENT', 'Consider Procurement'), ('CONSIDER_SCALEUP', 'Consider Scale-up'), ('ADDITIONAL_PILOT', 'Request Additional Pilot'), ('CLARIFICATION', 'Request Clarification'), ('DO_NOT_RECOMMEND', 'Do Not Recommend')], max_length=32)),
                ('narrative', models.TextField(blank=True)),
                ('scaleup_tips', models.JSONField(blank=True, default=dict)),
                ('evidence_report', models.TextField(blank=True)),
                ('officer_note', models.TextField(blank=True)),
                ('ai_demo', models.BooleanField(default=False)),
                ('ai_notice', models.TextField(blank=True)),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation', to='pilots.pilot')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
