# Generated by Django 5.2.17 on 2026-09-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('problem', 'Problem statement'), ('startup', 'Startup')], max_length=16)),
                ('entity_id', models.PositiveIntegerField()),
                ('vector', models.JSONField()),
                ('source_text', models.TextField()),
                ('model_name', models.CharField(max_length=160)),
                ('dimensions', models.PositiveIntegerField(default=384)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
    ]
