# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problem_statements', '0001_initial'),
        ('startups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ELIGIBILITY_CHECK', 'Eligibility check'), ('REJECTED_DEADLINE', 'Rejected — cannot meet pilot deadline'), ('UNDER_TECHNICAL_EVALUATION', 'Under technical evaluation'), ('CLARIFICATION_REQUIRED', 'Clarification required'), ('APPROVED_FOR_PILOT', 'Approved for pilot'), ('REJECTED', 'Rejected'), ('CONTRACT_PENDING', 'Contract pending'), ('PILOT_ACTIVE', 'Pilot active'), ('PILOT_COMPLETED', 'Pilot completed'), ('PILOT_CANCELLED', 'Pilot cancelled')], default='SUBMITTED', max_length=40)),
                ('eligibility_confirmed', models.BooleanField(default=False)),
                ('eligibility_checks', models.JSONField(default=dict)),
                ('pilot_readiness', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=8)),
                ('proposal_text', models.TextField(blank=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('clarification_request', models.TextField(blank=True)),
                ('clarification_response', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='problem_statements.problemstatement')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='startups.startup')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('startup', 'problem_statement')},
            },
        ),
    ]
