# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('pilots', '0001_initial'),
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('document_type', models.CharField(choices=[('DPIIT', 'DPIIT Recognition Certificate'), ('GST', 'GST Certificate'), ('INCORPORATION', 'Company Incorporation / CIN'), ('ISO_27001', 'ISO 27001'), ('ISO_9001', 'ISO 9001'), ('PAN', 'PAN'), ('TECHNICAL_PROPOSAL', 'Technical Proposal (PPT)'), ('SOLUTION', 'Solution / PS document'), ('SIGNED_CONTRACT', 'Signed pilot contract'), ('UNSIGNED_CONTRACT', 'Unsigned pilot contract'), ('WEEKLY_EVIDENCE', 'Weekly report evidence'), ('FINAL_EVIDENCE', 'Final report evidence'), ('OTHER', 'Other')], max_length=40)),
                ('object_key', models.CharField(max_length=400)),
                ('file_name', models.CharField(max_length=240)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('VERIFIED_VALID', 'Verified & valid'), ('EXPIRING_SOON', 'Expiring soon'), ('EXPIRED', 'Expired'), ('PENDING_VERIFICATION', 'Pending verification'), ('REJECTED', 'Rejected')], default='PENDING_VERIFICATION', max_length=32)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('no_expiry', models.BooleanField(default=False)),
                ('currently_valid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='applications.application')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='pilots.pilot')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacements', to='documents.document')),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='startups.startup')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
