# Generated by Django 5.2.17 on 2026-09-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('problem_statements', '0001_initial'),
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('location', models.CharField(max_length=240)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('joining_deadline', models.DateField(blank=True, null=True)),
                ('duration_weeks', models.PositiveIntegerField(default=12)),
                ('responsibilities', models.TextField(blank=True)),
                ('government_support', models.TextField(blank=True)),
                ('payment_conditions', models.TextField(blank=True)),
                ('reporting_frequency', models.CharField(default='Weekly', max_length=80)),
                ('security_requirements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CONTRACT_PENDING', 'Contract pending'), ('CONTRACT_ACCEPTED', 'Contract accepted'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=32)),
                ('kpi_locked', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('score_cache', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot', to='applications.application')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_pilots', to=settings.AUTH_USER_MODEL)),
                ('field_evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_pilots', to=settings.AUTH_USER_MODEL)),
                ('problem_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='problem_statements.problemstatement')),
                ('procurement_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_pilots', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilots', to='startups.startup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_week', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('DELAYED', 'Delayed')], default='PENDING', max_length=16)),
                ('order', models.PositiveIntegerField(default=1)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='pilots.pilot')),
            ],
            options={
                'ordering': ['order', 'due_week'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('target', models.FloatField()),
                ('unit', models.CharField(max_length=40)),
                ('weight', models.FloatField()),
                ('priority', models.CharField(choices=[('MUST_HAVE', 'MUST HAVE'), ('BETTER_TO_HAVE', 'BETTER TO HAVE'), ('NICE_TO_HAVE', 'NICE TO HAVE')], default='MUST_HAVE', max_length=24)),
                ('direction', models.CharField(choices=[('HIGHER_IS_BETTER', 'Higher is better'), ('LOWER_IS_BETTER', 'Lower is better')], default='HIGHER_IS_BETTER', max_length=24)),
                ('max_score', models.FloatField(default=120)),
                ('source', models.CharField(default='MANUAL', max_length=16)),
                ('order', models.PositiveIntegerField(default=1)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='pilots.pilot')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(max_length=48, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('CONTRACT_ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=32)),
                ('kpi_method', models.CharField(choices=[('MANUAL', 'Manual KPI entry'), ('EXTRACT', 'Extract KPIs from signed contract')], default='MANUAL', max_length=16)),
                ('body_text', models.TextField(blank=True)),
                ('unsigned_key', models.CharField(blank=True, max_length=400)),
                ('signed_key', models.CharField(blank=True, max_length=400)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('replacement_log', models.JSONField(blank=True, default=list)),
                ('extracted_kpis', models.JSONField(blank=True, default=list)),
                ('extraction_demo', models.BooleanField(default=False)),
                ('extraction_notice', models.TextField(blank=True)),
                ('kpis_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pilot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='pilots.pilot')),
            ],
        ),
    ]
